# Generated by Django 5.0.3 on 2024-03-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_bg', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
    ]
