# Generated by Django 5.0.3 on 2024-03-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dynamic_theme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
