# Generated by Django 5.0.3 on 2024-03-24 23:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_dynamic_theme", "0002_background_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='primary_bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
