# Generated by Django 5.0.3 on 2024-03-25 21:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0003_alter_background_primary_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name="background",
            name="primary_bg",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Primary Name",
            ),
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "background",
                    models.ManyToManyField(to="django_dynamic_theme.background"),
                ),
            ],
        ),
    ]
