# Generated by Django 5.0.3 on 2024-03-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dynamic_theme", "0004_alter_background_primary_bg_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="background",
        ),
        migrations.AddField(
            model_name="theme",
            name="background",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_dynamic_theme.background",
            ),
            preserve_default=False,
        ),
    ]
