# Generated by Django 5.0.3 on 2024-03-27 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0005_remove_theme_background_theme_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_theme.background'),
        ),
    ]
