# Generated by Django 5.0.3 on 2024-03-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0006_alter_theme_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('default',), name='Only one theme can be default.'),
        ),
    ]
