# Generated by Django 5.0.3 on 2024-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0007_theme_default_theme_only_one_theme_can_be_default_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
