# Generated by Django 5.0.3 on 2024-03-30 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0009_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='navbar',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_theme.navbar'),
        ),
    ]
