# Generated by Django 5.0.3 on 2024-04-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0010_theme_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='font_size',
            field=models.CharField(choices=[('xx-small', 'Xx Small'), ('x-small', 'X Small'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('x-large', 'X Large'), ('xx-large', 'Xx Large'), ('xxx-large', 'Xxx Large')], default='medium', max_length=20),
        ),
    ]
