# Generated by Django 5.0.3 on 2024-04-06 22:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0011_navbar_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
