# Generated by Django 5.0.3 on 2024-04-06 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0012_navbar_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='text_opacity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
