# Generated by Django 5.0.3 on 2024-04-06 23:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0013_navbar_text_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
