# Generated by Django 5.0.4 on 2024-05-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0014_alter_navbar_opacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('margin_left', models.CharField(max_length=50)),
                ('margin_right', models.CharField(max_length=50)),
                ('max_width', models.CharField(max_length=50)),
                ('item_align', models.CharField(max_length=50)),
                ('row_margin_top', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
