# Generated by Django 5.0.4 on 2024-05-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_theme', '0015_mediagallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='media_gallery',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_dynamic_theme.mediagallery'),
        ),
    ]
